### ISSUE TITLE
How to login? 

### ISSUE THREAD

**Issue by zekeadam** [erik73/addon-mail#24]
Admin web interface doesn't accept username and password from config file. How to log in?

**Comment by erik73** [comment]
Hi. 

The documentation is really missing. Sorry about that. 
you need to use FQDN when logging in. 
for example: admin@my.domain.com

Please report back if it works for you!

**Comment by zekeadam** [comment]
Thanks for the very quick reply!

I tried that but didn't work for me. I guess the problem is that I don't know how to set the my_hostname, domain_name fields. I only want to use the addon on my local network. I tried a few things like my using my DDNS address or local.hass.io but none of them worked.

**Comment by erik73** [comment]
I have just added som documentation that I will push as a new version in about 30 minutes.
To start testing the add-on, I suggest you reset the configuration to default values.
Since the database is already created, you have to use the phpMyadmin add-on to drop the database first. 
It is not possible to change the credentials and domain after the database creation. More about that in the documentation in about 30 minutes!

**Comment by erik73** [comment]
The database is called "postfixadmin"

**Comment by zekeadam** [comment]
It works! Deleting the DB did the trick, thank you!

**Comment by erik73** [comment]
Great. 
I just published a new version, and added some documentation. 
I will add more details later, but at least it is a start...

**Comment by erik73** [comment]
Closing this. Good luck!
